// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3G0YDvK29K_UZLOTh0NYvGlOmfWV497k',
    appId: '1:1024461466218:web:2dc52c5bd46e6eaa84b813',
    messagingSenderId: '1024461466218',
    projectId: 'xoxo-ecommerce-c4558',
    authDomain: 'xoxo-ecommerce-c4558.firebaseapp.com',
    storageBucket: 'xoxo-ecommerce-c4558.appspot.com',
    measurementId: 'G-9MR9HNXGRR',
    databaseURL: 'https://xoxo-ecommerce-c4558-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWn0OAu79R-P7_pXzMukvtLzzYhgGB5w',
    appId: '1:1024461466218:android:d916946505fe72f284b813',
    messagingSenderId: '1024461466218',
    projectId: 'xoxo-ecommerce-c4558',
    storageBucket: 'xoxo-ecommerce-c4558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmomGg1hy-YbNnyLEiq2e-vidZmCD6DZA',
    appId: '1:1024461466218:ios:913e8a58d677c41584b813',
    messagingSenderId: '1024461466218',
    projectId: 'xoxo-ecommerce-c4558',
    storageBucket: 'xoxo-ecommerce-c4558.appspot.com',
    iosBundleId: 'com.example.xoxoEcommerce',
    databaseURL: 'https://xoxo-ecommerce-c4558-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmomGg1hy-YbNnyLEiq2e-vidZmCD6DZA',
    appId: '1:1024461466218:ios:913e8a58d677c41584b813',
    messagingSenderId: '1024461466218',
    projectId: 'xoxo-ecommerce-c4558',
    storageBucket: 'xoxo-ecommerce-c4558.appspot.com',
    iosBundleId: 'com.example.xoxoEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3G0YDvK29K_UZLOTh0NYvGlOmfWV497k',
    appId: '1:1024461466218:web:ae4a57fd6360fca084b813',
    messagingSenderId: '1024461466218',
    projectId: 'xoxo-ecommerce-c4558',
    authDomain: 'xoxo-ecommerce-c4558.firebaseapp.com',
    storageBucket: 'xoxo-ecommerce-c4558.appspot.com',
    measurementId: 'G-MLVX1RP521',
  );
}
